### ISSUE TITLE
Default configuration doesn't work

### ISSUE THREAD

**Issue by guruevi** [systemd/systemd-netlogd#20] opened 2018-08-07 14:33 UTC
Since this crucial piece of systemd is not yet in Ubuntu distribution, I compiled it from scratch. No errors, I put in a configuration and enabled and started systemd-netlogd.

I get the following error:
Aug 07 10:30:26 dicom systemd[1]: Started Journal Syslog Unicast and Multicast Daemon.
Aug 07 10:30:27 dicom systemd[1]: systemd-netlogd.service: Main process exited, code=exited, status=1/FAILURE
Aug 07 10:30:27 dicom systemd[1]: systemd-netlogd.service: Failed with result 'exit-code'.

**Comment by ssahani** [comment] 2018-08-08 07:06
No info to debug with. Please start manually from command line ```SYSTEMD_LOG_LEVEL=debug ./systemd-netlogd'``` and paste the logs

**Comment by bachp** [comment] 2018-10-12 08:17
I think the problem is that the default `systemd-netlogd.conf` has the `Address` commented out. As `systemd-netlogd` doesn't know what to do in that case it just exists with exit code 1.

**Comment by daringer** [comment] 2019-07-02 23:10
Yes, can confirm that the example does not work out-of-the-box ... Despite that it seems mandatory to provide an IP and not a hostname as no resolving seems to happen

**Comment by ssahani** [comment] 2019-10-15 16:17
Yes you need to put the address.

**Closed by ssahani** 2019-10-15 16:17 UTC
